version: '3.1'

services:

  wordpress:
    container_name: wp-9  
    image: wordpress:latest
    restart: "no"
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      # copiar plugins 1 a 1 
      - ./mis-plugins/lab-custom-login/:/var/www/html/wp-content/plugins/lab-custom-login  
      - ./mis-plugins/version-info/:/var/www/html/wp-content/plugins/version-info  
      - ./mis-plugins/very-simple-contact-form/:/var/www/html/wp-content/plugins/very-simple-contact-form 
      - ./mis-plugins/wpvivid-backuprestore/:/var/www/html/wp-content/plugins/wpvivid-backuprestore 
      # copiar themes 1 a 1             
      - ./mis-temas/generatepress/:/var/www/html/wp-content/themes/generatepress  
      - ./mis-temas/twentytwelve/:/var/www/html/wp-content/themes/twentytwelve       
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
                
  db:
    container_name: mysql-9  
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password  
    restart: "no" 
    volumes:
      - ./db:/var/lib/mysql     
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}  

  phpmyadmin:
    container_name: phpmyadmin-9      
    depends_on:      
    - db    
    image: phpmyadmin/phpmyadmin    
    links:      
    - db    
    ports:      
    - "8080:80"    
    restart: "no" 
    
   


 